name: Build and deploy Python app to Azure Web App - Linker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd Linker_server
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          cd Linker_server
          zip -r ../deployment.zip ./*

      - name: Login to Azure using federated credentials
        uses: azure/login@v2
        with:
          client-id: 8a623831-ffdd-4ee1-96eb-09353c8e6607
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Linker'
          slot-name: 'Production'
          package: deployment.zip
