name: Build and deploy Python app to Azure Web App - Linker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  APP_NAME: 'Linker'
  RESOURCE_GROUP: 'your-resource-group-name'  # добавьте это
  PYTHON_APP_FOLDER: 'Linker_server'  # явно задаем имя папки

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.PYTHON_APP_FOLDER }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests  # новый шаг
        working-directory: ${{ env.PYTHON_APP_FOLDER }}
        run: |
          python -m pytest || echo "Tests failed"  # базовый вариант

      - name: Create deployment package
        run: |
          cd ${{ env.PYTHON_APP_FOLDER }} && zip -r ../deployment.zip ./*

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 8a623831-ffdd-4ee1-96eb-09353c8e6607
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}  
          package: deployment.zip