name: Build and deploy Python app to Azure Web App - Linker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (inside Linker_server)
        run: |
          cd Linker_server
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4E5A7AF1570D4B71A4D1D68608584386 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1FD1BE60FD24832A9AB64F6BE368C51 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE1B135170DA48728A4C33F840E2D1ED }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Linker'
          slot-name: 'Production'
          package: Linker_server
