name: Python Backend CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: "Linker"
  RESOURCE_GROUP: "Linker-resource-group"
  PYTHON_VERSION: "3.11"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

steps:
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ env.PYTHON_VERSION }}

  - name: Install dependencies
    working-directory: linker_server
    run: |
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then  # Фиксим: добавили пробелы и кавычки
        pip install -r requirements.txt
      else
        echo "⚠️ requirements.txt not found! Installing default packages..."
        pip install flask gunicorn
      fi

  - name: Login to Azure
    uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          package: .
          runtime: "PYTHON:${{ env.PYTHON_VERSION }}"